_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
attack_mode:
    value: gpatch
epochs:
    value: 40
num_of_patches:
    value: 1
patch_size:
    value: 64
run_mode:
    value: test
target_class:
    value: 932
target_models:
    value:
        - resnet50
training_models:
    value:
        - vgg16_bn
