_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
classes:
    value: 10
epochs:
    value: 1
input_dim:
    value: 100
